# Generated by Django 4.1.7 on 2023-06-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_alter_category_id_alter_customer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='ammount',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('new', 'Новый заказ.'), ('pending', 'Заказ в работе~'), ('finished', 'Заказ выполнен!')], default='new', max_length=10),
        ),
    ]
