# Generated by Django 4.1.7 on 2023-06-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_rename_ammount_orderproduct_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
            ],
        ),
    ]
